table_name = "exam"
class_num = "5"
"1限目開始" = "8 50"
"1限目終了" = "9 40"
"2限目開始" = "10 00"
"2限目終了" = "10 50"
"3限目開始" = "11 10"
"3限目終了" = "12 00"
"4限目開始" = "12 20"
"4限目終了" = "13 10"
"5限目開始" = "13 30"
"5限目終了" = "14 20"
